version: "3.8"

services:
  pms:
    build: .
    command: entrypoint.sh
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - "8085:8085"
    

  celery:
    build: .
    command: celery -A pms worker -l INFO
    depends_on:
      - pms
      - redis

  redis:
    image: "redis:alpine"
