# Generated by Django 4.2.16 on 2025-07-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_remove_shiftpoint_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyProductionReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Where to send the report', max_length=254, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
