# Generated by Django 4.2.16 on 2025-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_hourlyproductionreportrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PAGES', max_length=50, unique=True)),
                ('data', models.JSONField(help_text='Paste the entire PAGES JSON object here.')),
            ],
            options={
                'verbose_name': 'Pages configuration',
                'verbose_name_plural': 'Pages configurations',
            },
        ),
    ]
