# Generated by Django 4.2.16 on 2025-07-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_pagesconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagesConfig',
        ),
    ]
