# Generated by Django 4.2.23 on 2025-07-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0017_redrabbittype_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='qualitypdfdocument',
            name='category',
            field=models.CharField(choices=[('QA', 'Quality Alerts'), ('SI', 'Special Instruction'), ('TPC', 'TPC'), ('VAC', 'Visual Acceptance Criteria'), ('PMR', 'Part Marking Requirement'), ('CT', 'Certification Tag'), ('SA', 'Safety Alert')], default='QA', max_length=10),
        ),
    ]
