# Generated by Django 4.2.23 on 2025-06-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0017_redrabbittype_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewScrapSystemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='New Scrap System Category Name')),
                ('description', models.TextField(blank=True, verbose_name='New Scrap System Category Description')),
            ],
            options={
                'verbose_name': 'New Scrap System Category',
                'verbose_name_plural': 'New Scrap System Categories',
                'db_table': 'new_scrap_system_category',
            },
        ),
        migrations.CreateModel(
            name='NewScrapSystemOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='New Scrap System Operation Name')),
                ('description', models.TextField(blank=True, verbose_name='New Scrap System Operation Description')),
            ],
            options={
                'verbose_name': 'New Scrap System Operation',
                'verbose_name_plural': 'New Scrap System Operations',
                'db_table': 'new_scrap_system_operation',
            },
        ),
        migrations.CreateModel(
            name='NewScrapSystemPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='New Scrap System Part #')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='New Scrap System Part Description')),
            ],
            options={
                'verbose_name': 'New Scrap System Part Number',
                'verbose_name_plural': 'New Scrap System Part Numbers',
                'db_table': 'new_scrap_system_part_number',
            },
        ),
        migrations.AlterField(
            model_name='qualitypdfdocument',
            name='category',
            field=models.CharField(choices=[('QA', 'Quality Alerts'), ('SI', 'Special Instruction'), ('TPC', 'TPC'), ('VAC', 'Visual Acceptance Criteria'), ('PMR', 'Part Marking Requirement'), ('CT', 'Certification Tag'), ('SA', 'Safety Alert')], default='QA', max_length=10),
        ),
        migrations.CreateModel(
            name='NewScrapSystemScrapCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost associated with this part/operation/category', max_digits=10, verbose_name='New Scrap System Cost')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_costs', to='quality.newscrapsystemcategory', verbose_name='New Scrap System Category')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_costs', to='quality.newscrapsystemoperation', verbose_name='New Scrap System Operation')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_costs', to='quality.newscrapsystempartnumber', verbose_name='New Scrap System Part Number')),
            ],
            options={
                'verbose_name': 'New Scrap System Scrap Cost',
                'verbose_name_plural': 'New Scrap System Scrap Costs',
                'db_table': 'new_scrap_system_scrap_cost',
                'unique_together': {('part_number', 'operation', 'category')},
            },
        ),
    ]
