# Generated by Django 4.2.23 on 2025-07-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0026_alter_absenteereport_uploaded_at'),
        ('quality', '0018_scrapcategory_alter_qualitypdfdocument_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapSystemOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assets', models.ManyToManyField(blank=True, to='plant.asset')),
                ('scrap_categories', models.ManyToManyField(blank=True, to='quality.scrapcategory')),
            ],
        ),
    ]
