# Generated by Django 4.2.23 on 2025-06-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0018_newscrapsystemcategory_newscrapsystemoperation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newscrapsystemscrapcost',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='newscrapsystemscrapcost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newscrapsystemscrapcost',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='newscrapsystemscrapcost',
            name='part_number',
        ),
        migrations.DeleteModel(
            name='NewScrapSystemCategory',
        ),
        migrations.DeleteModel(
            name='NewScrapSystemOperation',
        ),
        migrations.DeleteModel(
            name='NewScrapSystemPartNumber',
        ),
        migrations.DeleteModel(
            name='NewScrapSystemScrapCost',
        ),
    ]
