# Generated by Django 4.2.23 on 2025-07-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0026_alter_absenteereport_uploaded_at'),
        ('quality', '0019_scrapsystemoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_submissions', to='plant.asset')),
                ('scrap_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_submissions', to='quality.scrapcategory')),
                ('scrap_system_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quality.scrapsystemoperation')),
            ],
        ),
    ]
