# Generated by Django 4.2.23 on 2025-06-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0019_alter_newscrapsystemscrapcost_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewScrapSystemScrapCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Enter the part number (free-form)', max_length=100, verbose_name='New Scrap System Part Number')),
                ('operation', models.CharField(help_text='Enter the operation name', max_length=100, verbose_name='New Scrap System Operation')),
                ('category', models.CharField(help_text='Enter the scrap category', max_length=100, verbose_name='New Scrap System Category')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Enter the cost for this part/operation/category', max_digits=10, verbose_name='New Scrap System Cost')),
            ],
            options={
                'verbose_name': 'New Scrap System Scrap Category',
                'verbose_name_plural': 'New Scrap System Scrap Categories',
                'db_table': 'new_scrap_system_scrap_category',
                'ordering': ['part_number', 'operation', 'category'],
                'unique_together': {('part_number', 'operation', 'category')},
            },
        ),
    ]
