# Generated by Django 4.2.23 on 2025-06-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0020_newscrapsystemscrapcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewScrapSystemScrapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.CharField(max_length=100, verbose_name='New Scrap System Machine')),
                ('part_number', models.CharField(max_length=100, verbose_name='New Scrap System Part #')),
                ('operation', models.CharField(max_length=100, verbose_name='New Scrap System Operation')),
                ('category', models.CharField(max_length=100, verbose_name='New Scrap System Category')),
                ('quantity', models.PositiveIntegerField(verbose_name='New Scrap System Qty')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New Scrap System $/unit')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='New Scrap System Total $')),
            ],
            options={
                'verbose_name': 'New Scrap System Scrap Entry',
                'verbose_name_plural': 'New Scrap System Scrap Entries',
                'db_table': 'new_scrap_system_scrap_entry',
                'ordering': ['-created_at'],
            },
        ),
    ]
