# Generated by Django 4.2.23 on 2025-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0026_alter_absenteereport_uploaded_at'),
        ('quality', '0021_newscrapsystemscrapentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscrapsystemscrapcategory',
            options={'ordering': ['part_number', 'operation', 'category']},
        ),
        migrations.AddField(
            model_name='newscrapsystemscrapcategory',
            name='machines',
            field=models.ManyToManyField(blank=True, related_name='scrap_categories', to='plant.asset', verbose_name='Associated Machines'),
        ),
        migrations.AlterField(
            model_name='newscrapsystemscrapcategory',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='newscrapsystemscrapcategory',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='newscrapsystemscrapcategory',
            name='operation',
            field=models.CharField(max_length=100, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='newscrapsystemscrapcategory',
            name='part_number',
            field=models.CharField(max_length=100, verbose_name='Part Number'),
        ),
    ]
