# Generated by Django 4.2.23 on 2025-07-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0021_scrapsubmission_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapsubmission',
            name='category_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapsubmission',
            name='machine',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapsubmission',
            name='operation_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapsubmission',
            name='part_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
