# Generated by Django 4.2.23 on 2025-07-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0022_scrapsubmission_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapcategory',
            options={'verbose_name_plural': 'Scrap categories'},
        ),
        migrations.AddField(
            model_name='scrapsubmission',
            name='operator_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
