# Generated by Django 4.2.23 on 2025-07-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0023_alter_scrapcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapsubmission',
            name='came_from_op',
            field=models.CharField(blank=True, default='', help_text='Optional: operation where this scrap originated', max_length=256),
        ),
    ]
