# Generated by Django 4.2.23 on 2025-07-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0025_alter_scrapsubmission_came_from_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapsubmission',
            name='came_from_op',
            field=models.CharField(blank=True, default='', help_text='Optional: operation where this scrap originated', max_length=256),
        ),
    ]
