# Generated by Django 4.2.23 on 2025-08-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0026_alter_scrapsubmission_came_from_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='scrapsystemoperation',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='operations', to='quality.program'),
        ),
    ]
