# Generated by Django 4.2.23 on 2025-08-07 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quality', '0026_alter_scrapsubmission_came_from_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(default=django.utils.timezone.now)),
                ('issuer_name', models.CharField(max_length=120)),
                ('reason', models.CharField(max_length=200)),
                ('process', models.CharField(max_length=120)),
                ('supplier_issue', models.BooleanField(default=False)),
                ('machine_number', models.CharField(blank=True, max_length=50)),
                ('reason_note', models.TextField(blank=True)),
                ('feature', models.CharField(blank=True, max_length=120)),
                ('current_process', models.TextField(blank=True)),
                ('changed_to', models.TextField(blank=True)),
                ('expiration_date', models.DateField()),
                ('expiration_notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tpc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
    ]
