# Generated by Django 4.2.23 on 2025-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0027_tpcrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpcrequest',
            name='part',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
