# Generated by Django 4.2.23 on 2025-08-11 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quality', '0028_tpcrequest_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPCApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='quality.tpcrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tpc', 'user')},
            },
        ),
    ]
