# Generated by Django 4.2.23 on 2025-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0029_tpcapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpcrequest',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
