# Generated by Django 4.2.23 on 2025-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0030_alter_tpcrequest_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpcrequest',
            name='machine_number',
        ),
        migrations.RemoveField(
            model_name='tpcrequest',
            name='part',
        ),
        migrations.AddField(
            model_name='tpcrequest',
            name='machines',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tpcrequest',
            name='parts',
            field=models.JSONField(default=list),
        ),
    ]
