# Generated by Django 4.2.23 on 2025-08-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0031_remove_tpcrequest_machine_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpcrequest',
            name='expiration_notes',
        ),
    ]
