# Generated by Django 4.2.23 on 2025-08-22 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quality', '0032_remove_tpcrequest_expiration_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_name', models.CharField(max_length=200)),
                ('approver_phone', models.CharField(max_length=50)),
                ('approver_response', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbal_approvals', to='quality.tpcrequest')),
            ],
        ),
    ]
