# Generated by Django 4.2.23 on 2025-08-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0033_verbalapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbalapproval',
            name='issuer_username',
            field=models.CharField(db_index=True, default=1, max_length=150),
            preserve_default=False,
        ),
    ]
