# Generated by Django 4.2.23 on 2025-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0034_verbalapproval_issuer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpcrequest',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
