# Generated by Django 4.2.23 on 2025-09-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0027_program_scrapsystemoperation_programs'),
        ('quality', '0035_tpcrequest_rejected'),
    ]

    operations = [
    ]
