# Generated by Django 4.2.23 on 2025-09-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0036_merge_20250903_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpcrequest',
            name='date_requested',
            field=models.DateTimeField(),
        ),
    ]
