# Generated by Django 4.2.23 on 2025-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0037_alter_tpcrequest_date_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpcrequest',
            name='qe_risk_assessment',
            field=models.TextField(blank=True),
        ),
    ]
