# Generated by Django 4.2.23 on 2025-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0038_tpcrequest_qe_risk_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpcrequest',
            name='repeat_deviation',
            field=models.BooleanField(default=False),
        ),
    ]
