# Generated by Django 4.2.23 on 2025-09-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0039_tpcrequest_repeat_deviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpcrequest',
            name='repeat_deviation',
        ),
        migrations.RemoveField(
            model_name='tpcrequest',
            name='supplier_issue',
        ),
    ]
