# Generated by Django 4.2.16 on 2025-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_query', '0004_oamachinetargets_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='oamachinetargets',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
