# Generated by Django 4.2.16 on 2025-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_query', '0005_oamachinetargets_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='oamachinetargets',
            name='isDeleted',
            field=models.BooleanField(default=False, help_text='Soft‑delete flag; set to True to hide this record'),
        ),
    ]
