# Generated by Django 4.2.16 on 2025-04-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_query', '0006_oamachinetargets_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='oamachinetargets',
            name='part',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
