# Generated by Django 4.2.16 on 2025-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_query', '0006_oamachinetargets_isdeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly_Production_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=20)),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target', models.IntegerField()),
            ],
            options={
                'ordering': ['-year', '-week'],
            },
        ),
    ]
