# Generated by Django 4.2.16 on 2025-04-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_alter_setupfor_created_at_alter_setupfor_since'),
        ('plant', '0006_alter_assetcycletimes_cycle_time'),
    ]

    operations = [
    ]
