# Generated by Django 4.2.16 on 2025-05-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_merge_20250422_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDowntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50, verbose_name='Line')),
                ('machine', models.CharField(max_length=50, verbose_name='Machine')),
                ('category', models.CharField(help_text="e.g. 'MAT'", max_length=16, verbose_name='Category')),
                ('subcategory', models.CharField(help_text="e.g. 'MAT-DEF'", max_length=20, verbose_name='Subcategory')),
                ('code', models.CharField(help_text='Same as subcategory', max_length=20, verbose_name='Downtime Code')),
                ('start_epoch', models.BigIntegerField(verbose_name='Start (epoch)')),
                ('closeout_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
