# Generated by Django 4.2.16 on 2025-05-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_merge_20250422_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSensorEmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to receive temp sensor alerts', max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Temp Sensor Email',
                'verbose_name_plural': 'Temp Sensor Email List',
            },
        ),
    ]
