# Generated by Django 4.2.16 on 2025-05-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_machinedowntimeevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedowntimeevent',
            name='category',
            field=models.TextField(verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='machinedowntimeevent',
            name='subcategory',
            field=models.TextField(verbose_name='Subcategory'),
        ),
    ]
