# Generated by Django 4.2.16 on 2025-05-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_tempsensoremaillist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsensoremaillist',
            name='email_sent',
            field=models.BigIntegerField(blank=True, help_text='Last alert sent (epoch seconds)', null=True),
        ),
    ]
