# Generated by Django 4.2.16 on 2025-05-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_alter_machinedowntimeevent_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinedowntimeevent',
            old_name='created_at',
            new_name='created_at_UTC',
        ),
        migrations.RenameField(
            model_name='machinedowntimeevent',
            old_name='updated_at',
            new_name='updated_at_UTC',
        ),
    ]
