# Generated by Django 4.2.16 on 2025-06-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_tempsensoremaillist_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenteeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('pay_date', models.DateField()),
                ('pay_code', models.CharField(max_length=100)),
                ('pay_category', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_group_name', models.CharField(max_length=255)),
                ('shift_rotation_description', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
