# Generated by Django 4.2.16 on 2025-05-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_rename_created_at_machinedowntimeevent_created_at_utc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedowntimeevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinedowntimeevent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
