# Generated by Django 4.2.16 on 2025-05-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0011_machinedowntimeevent_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinedowntimeevent',
            name='closeout_timestamp',
        ),
        migrations.AddField(
            model_name='machinedowntimeevent',
            name='closeout_epoch',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Closeout (epoch)'),
        ),
    ]
