# Generated by Django 4.2.16 on 2025-05-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0012_remove_machinedowntimeevent_closeout_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedowntimeevent',
            name='labour_type',
            field=models.CharField(choices=[('OPERATOR', 'Operator can fix'), ('ELECTRICIAN', 'Need Electrician'), ('TECH', 'Need Tech'), ('MILLWRIGHT', 'Need Millwright')], default='OPERATOR', help_text='Who is needed to fix this downtime', max_length=20),
        ),
    ]
