# Generated by Django 4.2.16 on 2025-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0013_machinedowntimeevent_labour_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedowntimeevent',
            name='assigned_to',
            field=models.CharField(blank=True, default='', help_text='Username of the labourer this is assigned to', max_length=100),
        ),
    ]
