# Generated by Django 4.2.16 on 2025-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0014_machinedowntimeevent_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedowntimeevent',
            name='closeout_comment',
            field=models.TextField(blank=True, help_text='What the labourer did to fix the issue when closing out', null=True, verbose_name='Close-out Comment'),
        ),
    ]
