# Generated by Django 4.2.16 on 2025-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0015_machinedowntimeevent_closeout_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50, unique=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower numbers are higher priority')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
