# Generated by Django 4.2.16 on 2025-05-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0016_linepriority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinedowntimeevent',
            name='labour_type',
        ),
        migrations.AddField(
            model_name='machinedowntimeevent',
            name='labour_types',
            field=models.JSONField(blank=True, default=list, help_text='List of labour roles needed (one or more of OPERATOR,ELECTRICIAN,TECH,MILLWRIGHT)'),
        ),
    ]
