# Generated by Django 4.2.16 on 2025-05-05 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0017_remove_machinedowntimeevent_labour_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_epoch', models.BigIntegerField()),
                ('leave_epoch', models.BigIntegerField(blank=True, null=True)),
                ('join_comment', models.TextField(blank=True, default='')),
                ('leave_comment', models.TextField(blank=True, null=True)),
                ('total_minutes', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='plant.machinedowntimeevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-join_epoch'],
                'unique_together': {('event', 'user', 'join_epoch')},
            },
        ),
    ]
