# Generated by Django 4.2.16 on 2025-05-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0018_downtimeparticipation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinedowntimeevent',
            name='assigned_to',
        ),
    ]
