# Generated by Django 4.2.16 on 2025-05-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_tempsensoremaillist_email_sent'),
        ('plant', '0019_remove_machinedowntimeevent_assigned_to'),
    ]

    operations = [
    ]
