# Generated by Django 4.2.16 on 2025-05-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0020_merge_20250512_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedowntimeevent',
            name='employee_id',
            field=models.TextField(blank=True, help_text='(optional) ID of the person who logged this downtime', null=True, verbose_name='Employee ID'),
        ),
    ]
