# Generated by Django 4.2.16 on 2025-05-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0021_machinedowntimeevent_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique downtime code, e.g. MECH-TOOL', max_length=20, unique=True, verbose_name='Code')),
                ('category', models.CharField(help_text='High‐level category, e.g. Mechanical / Equipment Failure', max_length=100, verbose_name='Category')),
                ('subcategory', models.CharField(help_text='Human‐readable subcategory, e.g. Tooling Failure', max_length=100, verbose_name='Subcategory')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this lookup row was last changed', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Downtime Code',
                'verbose_name_plural': 'Downtime Codes',
                'ordering': ['category', 'subcategory', 'code'],
            },
        ),
    ]
