# Generated by Django 4.2.16 on 2025-05-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0022_downtimecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSpine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.TextField()),
                ('operation', models.TextField()),
                ('machine_name', models.TextField()),
                ('part_number', models.TextField()),
                ('cycle_time', models.FloatField()),
                ('cycle_time_effective_date', models.BigIntegerField(help_text='Epoch timestamp (in seconds) when this cycle time takes effect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plant Spine',
                'verbose_name_plural': 'Plant Spine',
                'db_table': 'plant_spine',
                'ordering': ['-created_at'],
            },
        ),
    ]
