# Generated by Django 4.2.16 on 2025-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0022_downtimecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedowntimeevent',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Optional, same as subcategory if provided', max_length=20, verbose_name='Downtime Code'),
        ),
        migrations.AlterField(
            model_name='machinedowntimeevent',
            name='subcategory',
            field=models.TextField(blank=True, default='', help_text='Optional sub-category', verbose_name='Subcategory'),
        ),
    ]
