# Generated by Django 4.2.16 on 2025-05-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0023_plantspine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantspine',
            options={'verbose_name': 'Plant Spine Config', 'verbose_name_plural': 'Plant Spine Configs'},
        ),
        migrations.RemoveField(
            model_name='plantspine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plantspine',
            name='cycle_time',
        ),
        migrations.RemoveField(
            model_name='plantspine',
            name='cycle_time_effective_date',
        ),
        migrations.RemoveField(
            model_name='plantspine',
            name='line_name',
        ),
        migrations.RemoveField(
            model_name='plantspine',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='plantspine',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='plantspine',
            name='part_number',
        ),
        migrations.AddField(
            model_name='plantspine',
            name='data',
            field=models.JSONField(default=list, help_text='Full lines → operations → machines nested structure'),
        ),
        migrations.AddField(
            model_name='plantspine',
            name='name',
            field=models.CharField(default='default', help_text="Identifier for this configuration (e.g. 'default')", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='plantspine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this JSON blob was last modified'),
        ),
    ]
