# Generated by Django 4.2.16 on 2025-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0023_alter_machinedowntimeevent_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(help_text='Production line this machine lives on', max_length=50, verbose_name='Line')),
                ('operation', models.CharField(help_text='Operation or process name', max_length=100, verbose_name='Operation')),
                ('machine_number', models.CharField(help_text='Unique number or code for the machine', max_length=50, verbose_name='Machine #')),
                ('is_tracked', models.BooleanField(default=True, help_text='Whether downtime is being recorded for this machine', verbose_name='Tracked?')),
                ('created_at_UTC', models.DateTimeField(auto_now_add=True, help_text='When this machine record was created (UTC)')),
                ('updated_at_UTC', models.DateTimeField(auto_now=True, help_text='When this machine record was last updated (UTC)')),
            ],
            options={
                'verbose_name': 'Downtime Machine',
                'verbose_name_plural': 'Downtime Machines',
                'ordering': ['line', 'operation', 'machine_number'],
                'unique_together': {('line', 'operation', 'machine_number')},
            },
        ),
    ]
