# Generated by Django 4.2.23 on 2025-06-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_absenteereport'),
        ('plant', '0024_downtimemachine'),
    ]

    operations = [
    ]
