# Generated by Django 4.2.16 on 2025-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0024_downtimemachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatBreakEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('1', 'Area 1'), ('2', 'Area 2'), ('3', 'Area 3')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
