# Generated by Django 4.2.16 on 2025-06-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0025_heatbreakentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatbreakentry',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
