# Generated by Django 4.2.23 on 2025-07-02 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0025_merge_0010_absenteereport_0024_downtimemachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenteereport',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
