# Generated by Django 4.2.16 on 2025-08-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0026_alter_absenteereport_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDowntimeEventTEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50, verbose_name='Line')),
                ('machine', models.CharField(max_length=50, verbose_name='Machine')),
                ('category', models.TextField(verbose_name='Category')),
                ('subcategory', models.TextField(blank=True, default='', help_text='Optional sub-category', verbose_name='Subcategory')),
                ('code', models.CharField(blank=True, default='', help_text='Optional, same as subcategory if provided', max_length=20, verbose_name='Downtime Code')),
                ('start_epoch', models.BigIntegerField(verbose_name='Start (epoch)')),
                ('closeout_epoch', models.BigIntegerField(blank=True, null=True, verbose_name='Closeout (epoch)')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_UTC', models.DateTimeField(auto_now_add=True)),
                ('updated_at_UTC', models.DateTimeField(auto_now=True)),
                ('labour_types', models.JSONField(blank=True, default=list, help_text='List of labour roles needed (one or more of OPERATOR,ELECTRICIAN,TECH,MILLWRIGHT)')),
                ('employee_id', models.TextField(blank=True, help_text='(optional) ID of the person who logged this downtime', null=True, verbose_name='Employee ID')),
                ('closeout_comment', models.TextField(blank=True, help_text='What the labourer did to fix the issue when closing out', null=True, verbose_name='Close-out Comment')),
            ],
        ),
    ]
