# Generated by Django 4.2.16 on 2025-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0026_alter_heatbreakentry_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatbreakentry',
            name='return_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heatbreakentry',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heatbreakentry',
            name='zone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
