# Generated by Django 4.2.23 on 2025-08-14 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0026_alter_absenteereport_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('visitor_type', models.CharField(choices=[('contractor', 'Contractor'), ('corporate', 'Corporate'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosts', models.ManyToManyField(related_name='hosted_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
