# Generated by Django 4.2.23 on 2025-08-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0027_heatbreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatbreak',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='heatbreak',
            name='start_time',
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='end_ts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='start_ts',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
