# Generated by Django 4.2.16 on 2025-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0027_heatbreakentry_return_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatbreakentry',
            name='humidex',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
