# Generated by Django 4.2.16 on 2025-08-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0027_machinedowntimeeventtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedowntimeeventtest',
            name='work_order_id',
            field=models.IntegerField(blank=True, default=None, help_text='ID returned by the work-order API', null=True, verbose_name='Work Order #'),
        ),
    ]
