# Generated by Django 4.2.23 on 2025-08-20 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0028_remove_heatbreak_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatbreak',
            name='end_ts',
        ),
        migrations.RemoveField(
            model_name='heatbreak',
            name='start_ts',
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
