# Generated by Django 4.2.16 on 2025-06-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_absenteereport'),
        ('plant', '0028_heatbreakentry_humidex'),
    ]

    operations = [
    ]
