# Generated by Django 4.2.16 on 2025-06-25 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0029_merge_0010_absenteereport_0028_heatbreakentry_humidex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeatBreakEntry',
        ),
        migrations.AlterField(
            model_name='absenteereport',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
