# Generated by Django 4.2.23 on 2025-08-20 14:56

from django.db import migrations, models
import plant.models.heat_break_models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0029_remove_heatbreak_end_ts_remove_heatbreak_start_ts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heatbreak',
            options={'ordering': ['-created_at_epoch']},
        ),
        migrations.RemoveField(
            model_name='heatbreak',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='heatbreak',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='heatbreak',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='heatbreak',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='created_at_epoch',
            field=models.BigIntegerField(default=plant.models.heat_break_models.unix_now, editable=False),
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='end_time_epoch',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='start_time_epoch',
            field=models.BigIntegerField(default=plant.models.heat_break_models.unix_now),
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='updated_at_epoch',
            field=models.BigIntegerField(default=plant.models.heat_break_models.unix_now, editable=False),
        ),
    ]
