# Generated by Django 4.2.16 on 2025-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0030_delete_heatbreakentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentHeatBreakEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField()),
                ('humidex', models.FloatField()),
                ('recommendation', models.CharField(max_length=100)),
                ('sent_on_break_epoch', models.BigIntegerField(blank=True, help_text='Timestamp (in seconds since epoch) when supervisor actually sent them on break', null=True)),
                ('supervisor_id', models.IntegerField(blank=True, help_text='ID of the supervisor who sent them on break', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this alert was recorded in the DB')),
            ],
        ),
    ]
