# Generated by Django 4.2.23 on 2025-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0030_alter_heatbreak_options_remove_heatbreak_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatbreak',
            name='turned_off_by',
        ),
        migrations.RemoveField(
            model_name='heatbreak',
            name='turned_on_by',
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='turned_off_by_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='turned_on_by_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
