# Generated by Django 4.2.23 on 2025-08-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0031_remove_heatbreak_turned_off_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatbreak',
            name='turned_off_by_username',
        ),
        migrations.RemoveField(
            model_name='heatbreak',
            name='turned_on_by_username',
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='turned_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heatbreaks_stopped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heatbreak',
            name='turned_on_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heatbreaks_started', to=settings.AUTH_USER_MODEL),
        ),
    ]
