# Generated by Django 4.2.23 on 2025-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0033_remove_heatbreak_turned_off_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatbreak',
            name='machine_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
