# Generated by Django 4.2.23 on 2025-08-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0034_heatbreak_machine_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('parts', models.ManyToManyField(blank=True, related_name='programs', to='plant.part')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='plant.part')),
                ('program', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='plant.program')),
            ],
        ),
    ]
