# Generated by Django 4.2.23 on 2025-08-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0035_program_programpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpart',
            name='part',
        ),
        migrations.RemoveField(
            model_name='programpart',
            name='program',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ProgramPart',
        ),
    ]
