# Generated by Django 4.2.23 on 2025-09-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0027_emailrecipient_emailcampaign'),
        ('plant', '0036_remove_programpart_part_remove_programpart_program_and_more'),
    ]

    operations = [
    ]
