# Generated by Django 4.2.23 on 2025-09-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0036_remove_programpart_part_remove_programpart_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('group_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pay Code Group',
                'verbose_name_plural': 'Pay Code Groups',
            },
        ),
        migrations.AddField(
            model_name='absenteereport',
            name='pay_group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
