# Generated by Django 4.2.23 on 2025-09-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0037_paycodegroup_absenteereport_pay_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenteereport',
            name='is_scheduled',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paycodegroup',
            name='is_scheduled',
            field=models.BooleanField(default=True),
        ),
    ]
