# Generated by Django 4.2.23 on 2025-09-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0038_absenteereport_is_scheduled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRotationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_text', models.CharField(db_index=True, max_length=255, unique=True)),
                ('shift', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Shift Rotation Map',
                'verbose_name_plural': 'Shift Rotation Maps',
            },
        ),
        migrations.AddField(
            model_name='absenteereport',
            name='shift',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
