# Generated by Django 4.2.23 on 2025-09-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0037_merge_20250903_0947'),
        ('plant', '0038_absenteereport_is_scheduled_and_more'),
    ]

    operations = [
    ]
