# Generated by Django 4.2.23 on 2025-09-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0028_machinedowntimeeventtest_work_order_id'),
        ('plant', '0038_absenteereport_is_scheduled_and_more'),
    ]

    operations = [
    ]
