# Generated by Django 4.2.23 on 2025-09-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0039_merge_20250909_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimeparticipation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='plant.machinedowntimeeventtest'),
        ),
    ]
