# Generated by Django 4.2.23 on 2025-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0039_shiftrotationmap_absenteereport_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenteereport',
            name='uploaded_by',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
