# Generated by Django 4.2.23 on 2025-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0041_downtimecodenewtest_lineprioritynewtest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtimemachinenewtest',
            options={'ordering': ['line', 'operation', 'machine_number'], 'verbose_name': 'Downtime Machine', 'verbose_name_plural': 'NEWTEST Downtime Machines'},
        ),
        migrations.AddField(
            model_name='machinedowntimeeventnewtest',
            name='work_order_id',
            field=models.IntegerField(blank=True, default=None, help_text='ID returned by the work-order API', null=True, verbose_name='Work Order #'),
        ),
    ]
