# Generated by Django 4.2.23 on 2025-09-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0042_alter_downtimemachinenewtest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedowntimeeventnewtest',
            name='closedout_by',
            field=models.CharField(blank=True, help_text='Username of the person who closed out the downtime event', max_length=150, null=True, verbose_name='Closed-out By'),
        ),
    ]
