# Generated by Django 4.2.23 on 2025-09-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0043_machinedowntimeeventnewtest_closedout_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaZoneNEWTEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Area/Zone')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_at_UTC', models.DateTimeField(auto_now_add=True)),
                ('updated_at_UTC', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area / Zone',
                'verbose_name_plural': 'NEWTEST Area / Zones',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='downtimemachinenewtest',
            name='created_at_UTC',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='downtimemachinenewtest',
            name='is_tracked',
            field=models.BooleanField(default=True, verbose_name='Tracked?'),
        ),
        migrations.AlterField(
            model_name='downtimemachinenewtest',
            name='line',
            field=models.CharField(max_length=50, verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='downtimemachinenewtest',
            name='machine_number',
            field=models.CharField(max_length=50, verbose_name='Machine #'),
        ),
        migrations.AlterField(
            model_name='downtimemachinenewtest',
            name='operation',
            field=models.CharField(max_length=100, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='downtimemachinenewtest',
            name='updated_at_UTC',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='downtimemachinenewtest',
            name='areazone',
            field=models.ForeignKey(blank=True, help_text='Optional Area/Zone this machine belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='plant.areazonenewtest'),
        ),
    ]
